### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by nicoddemus** [comment]
Sorry, ended up merging https://github.com/conda-forge/pytest-replay-feedstock/pull/6 first. Could you please rebase over `master`? Thanks.

Alternatively, we can wait for the next release to apply this improvements over the bot's PR.

**Comment by marcelotrevisani** [comment]
> Sorry, ended up merging #6 first. Could you please rebase over `master`? Thanks.
> 
> Alternatively, we can wait for the next release to apply this improvements over the bot's PR.

Sure, it can wait it then! :)

**Comment by nicoddemus** [comment]
👍

**Pull request closed without merging**
